"use strict";
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const now = () => new Date().toISOString();
const id = (p) => `${p}_${crypto.randomUUID()}`;
const fileFor = (dir) => path.join(dir, "life", "distill-me-identity-facts.json");
function read(dir) { const p=fileFor(dir); try { return JSON.parse(fs.readFileSync(p,"utf8")); } catch { return {version:1,items:[],drafts:[],audit:[]}; } }
function write(dir, data) { fs.mkdirSync(path.dirname(fileFor(dir)),{recursive:true}); fs.writeFileSync(fileFor(dir),JSON.stringify(data,null,2),"utf8"); }
function audit(data, action, itemId, meta={}) { data.audit.unshift({id:id("audit"),action,itemId:itemId||null,at:now(),...meta}); data.audit=data.audit.slice(0,200); }
function summary(data) { const active=data.items.filter(x=>["confirmed","edited"].includes(x.status)); return {version:data.version,identity:active.filter(x=>x.category==="identity"),experiences:active.filter(x=>x.category==="experience"),facts:active.filter(x=>x.category==="fact"),pending:data.items.filter(x=>x.status==="proposed"),counts:{identity:active.filter(x=>x.category==="identity").length,experience:active.filter(x=>x.category==="experience").length,fact:active.filter(x=>x.category==="fact").length,pending:data.items.filter(x=>x.status==="proposed").length}}; }
function createDraft(dir, input) { const d=read(dir); const draft={id:id("draft"),text:String(input?.text||"").slice(0,12000),sourceName:String(input?.sourceName||"用户直接输入"),sourceKind:input?.sourceKind||"direct",createdAt:now(),status:"created"}; d.drafts.unshift(draft); audit(d,"create_input",draft.id,{sourceKind:draft.sourceKind}); write(dir,d); return {id:draft.id}; }
function materialize(dir,draftId,result) { const d=read(dir), draft=d.drafts.find(x=>x.id===draftId); if(!draft) throw new Error("未找到输入草稿"); const rows=[]; for(const category of ["identity","experience","fact"]) for(const raw of result?.[category]||[]) { const statement=String(raw.statement||raw.title||raw||"").trim(); if(!statement) continue; const conflict=category==="identity"&&d.items.some(x=>x.category==="identity"&&["confirmed","edited"].includes(x.status)&&x.statement!==statement); rows.push({id:id("distill"),category,statement,status:"proposed",sourceRefs:[draft.id],evidenceRefs:[{sourceName:draft.sourceName,sourceKind:draft.sourceKind,excerpt:draft.text.slice(0,240),direct:draft.sourceKind==="direct"}],confidence:raw.confidence||"medium",conflict,createdAt:now(),updatedAt:now(),confirmedAt:null,version:1,audit:{createdBy:"system"}}); } d.items.push(...rows); draft.status="generated"; audit(d,"generate",draft.id,{count:rows.length}); write(dir,d); return {draftId,items:rows,snapshot:summary(d)}; }
function transition(dir,itemId,action,patch) { const d=read(dir), item=d.items.find(x=>x.id===itemId); if(!item) throw new Error("未找到记录"); if(action==="confirm"){item.status=patch&&patch.statement!==undefined?"edited":"confirmed";item.confirmedAt=now();} if(action==="edit"){item.statement=String(patch?.statement||item.statement).slice(0,1000);item.status="edited";item.confirmedAt=now();} if(action==="reject")item.status="rejected"; if(action==="revoke")item.status="revoked"; if(action==="delete")item.status="deleted"; item.updatedAt=now();item.version+=1;audit(d,action,itemId);write(dir,d);return {item,snapshot:summary(d)}; }
function exportSnapshot(dir,outDir){const d=read(dir),s=summary(d),target=path.join(outDir||path.join(dir,"exports"),`主体档案-${new Date().toISOString().slice(0,10)}.json`);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,JSON.stringify({version:s.version,exportedAt:now(),...s,auditSummary:d.audit.map(({action,itemId,at})=>({action,itemId,at}))},null,2));return {path:target};}
function context(dir){const s=summary(read(dir));return {identity:s.identity.map(x=>x.statement),experiences:s.experiences.map(x=>x.statement),facts:s.facts.map(x=>x.statement)};}
module.exports={read,summary,createDraft,materialize,transition,exportSnapshot,context};
