"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("digitalMe", {
  getConfig: () => ipcRenderer.invoke("config:get"),
  getRuntimeStamp: () => ipcRenderer.invoke("runtime:getStamp"),
  setConfig: (cfg) => ipcRenderer.invoke("config:set", cfg),
  clearApiKey: () => ipcRenderer.invoke("config:clearApiKey"),
  clearExtensionSecret: (payload) => ipcRenderer.invoke("secrets:clearExtensionEnv", payload),
  loadPackage: () => ipcRenderer.invoke("package:load"),
  getLifeGraph: (opts) => ipcRenderer.invoke("life:getGraph", opts),
  getCognition: () => ipcRenderer.invoke("life:getCognition"),
  generateCognitionReport: () => ipcRenderer.invoke("life:generateCognitionReport"),
  upsertLifePerson: (payload) => ipcRenderer.invoke("life:upsertPerson", payload),
  updateInference: (payload) => ipcRenderer.invoke("life:updateInference", payload),
  updatePersonStatus: (payload) => ipcRenderer.invoke("life:updatePerson", payload),
  updateMindHook: (payload) => ipcRenderer.invoke("life:updateMindHook", payload),
  distillMindHooks: () => ipcRenderer.invoke("life:distillMindHooks"),
  applyMindHooks: () => ipcRenderer.invoke("life:applyMindHooks"),
  markMindHooksDistilled: (ids) => ipcRenderer.invoke("life:markMindHooksDistilled", ids),
  upsertLifeEvent: (payload) => ipcRenderer.invoke("life:upsertEvent", payload),
  deleteLifeEvent: (id) => ipcRenderer.invoke("life:deleteEvent", id),
  getBoundaries: () => ipcRenderer.invoke("policies:getBoundaries"),
  addBoundary: (payload) => ipcRenderer.invoke("policies:addBoundary", payload),
  updateBoundary: (payload) => ipcRenderer.invoke("policies:updateBoundary", payload),
  removeBoundary: (payload) => ipcRenderer.invoke("policies:removeBoundary", payload),
  restoreBoundaryDefaults: (payload) => ipcRenderer.invoke("policies:restoreDefaults", payload),
  sendChat: (payload) => ipcRenderer.invoke("chat:send", payload),
  stopChat: (payload) => ipcRenderer.invoke("chat:stop", payload),
  pickAttachments: () => ipcRenderer.invoke("chat:pickAttachments"),
  onChatProgress: (cb) => {
    const handler = (_e, data) => cb(data);
    ipcRenderer.on("chat:progress", handler);
    return () => ipcRenderer.removeListener("chat:progress", handler);
  },
  onResearchProgress: (cb) => {
    const handler = (_e, data) => cb(data);
    ipcRenderer.on("research:progress", handler);
    return () => ipcRenderer.removeListener("research:progress", handler);
  },
  // Sessions
  listSessions: () => ipcRenderer.invoke("sessions:list"),
  getSession: (id) => ipcRenderer.invoke("sessions:get", id),
  createSession: (opts) => ipcRenderer.invoke("sessions:create", opts),
  saveSession: (session) => ipcRenderer.invoke("sessions:save", session),
  renameSession: (payload) => ipcRenderer.invoke("sessions:rename", payload),
  deleteSession: (id) => ipcRenderer.invoke("sessions:delete", id),
  setActiveSession: (id) => ipcRenderer.invoke("sessions:setActive", id),
  // Exports
  exportMarkdown: (payload) => ipcRenderer.invoke("output:exportMarkdown", payload),
  exportDocx: (payload) => ipcRenderer.invoke("output:exportDocx", payload),
  openDraftsFolder: () => ipcRenderer.invoke("output:openDraftsFolder"),
  getDraftsDir: () => ipcRenderer.invoke("output:getDraftsDir"),
  // Deliverables library
  listLibrary: () => ipcRenderer.invoke("library:list"),
  getLibraryItem: (id) => ipcRenderer.invoke("library:get", id),
  saveLibraryItem: (item) => ipcRenderer.invoke("library:save", item),
  deleteLibraryItem: (id) => ipcRenderer.invoke("library:delete", id),
  getLibraryTemplates: () => ipcRenderer.invoke("library:templates"),
  getScenarioPacks: () => ipcRenderer.invoke("library:scenarioPacks"),
  prepareScenario: (packId) => ipcRenderer.invoke("scenarios:prepare", packId),
  getCapabilitySurface: (payload) => ipcRenderer.invoke("capabilities:surface", payload),
  createFromTemplate: (payload) => ipcRenderer.invoke("library:createFromTemplate", payload),
  createBlankLibrary: (payload) => ipcRenderer.invoke("library:createBlank", payload),
  importArtifactToLibrary: (payload) => ipcRenderer.invoke("library:importArtifact", payload),
  exportLibraryItem: (payload) => ipcRenderer.invoke("library:export", payload),
  // Research
  listResearch: () => ipcRenderer.invoke("research:list"),
  getResearch: (id) => ipcRenderer.invoke("research:get", id),
  getActiveResearch: () => ipcRenderer.invoke("research:active"),
  createResearch: (payload) => ipcRenderer.invoke("research:create", payload),
  saveResearch: (item) => ipcRenderer.invoke("research:save", item),
  deleteResearch: (id) => ipcRenderer.invoke("research:delete", id),
  setActiveResearch: (id) => ipcRenderer.invoke("research:setActive", id),
  setResearchStage: (payload) => ipcRenderer.invoke("research:setStage", payload),
  setResearchProgress: (payload) => ipcRenderer.invoke("research:setProgress", payload),
  addResearchMaterial: (payload) => ipcRenderer.invoke("research:addMaterial", payload),
  addResearchSource: (payload) => ipcRenderer.invoke("research:addSource", payload),
  removeResearchMaterial: (payload) => ipcRenderer.invoke("research:removeMaterial", payload),
  removeResearchSource: (payload) => ipcRenderer.invoke("research:removeSource", payload),
  addResearchArtifact: (payload) => ipcRenderer.invoke("research:addArtifact", payload),
  removeResearchArtifact: (payload) => ipcRenderer.invoke("research:removeArtifact", payload),
  runResearchCheck: (payload) => ipcRenderer.invoke("research:runCheck", payload),
  runResearchClaimAudit: (payload) => ipcRenderer.invoke("research:runClaimAudit", payload),
  getResearchStages: () => ipcRenderer.invoke("research:stages"),
  getResearchProgressSteps: () => ipcRenderer.invoke("research:progressSteps"),
  getResearchMethodPacks: () => ipcRenderer.invoke("research:methodPacks"),
  getResearchSourceActions: () => ipcRenderer.invoke("research:sourceActions"),
  prepareResearchMethod: (packId) => ipcRenderer.invoke("research:prepareMethod", packId),
  exportResearchFinal: (payload) => ipcRenderer.invoke("research:exportFinal", payload),
  sendResearchToWriting: (payload) => ipcRenderer.invoke("research:sendToWriting", payload),
  exportResearchDeliverable: (payload) => ipcRenderer.invoke("research:exportDeliverable", payload),
  fetchResearchSourceExcerpt: (payload) => ipcRenderer.invoke("research:fetchSourceExcerpt", payload),
  prepareResearchScene: () => ipcRenderer.invoke("research:prepareScene"),
  prepareCodeScene: () => ipcRenderer.invoke("code:prepareScene"),
  buildCodeDelegationHint: (payload) => ipcRenderer.invoke("code:buildDelegationHint", payload),
  discoverResearchSources: (payload) => ipcRenderer.invoke("research:discoverSources", payload),
  runResearchAgentLoop: (payload) => ipcRenderer.invoke("research:runAgentLoop", payload),
  addResearchLocalSource: (payload) => ipcRenderer.invoke("research:addLocalSource", payload),
  validateResearchGrounded: (payload) => ipcRenderer.invoke("research:validateGrounded", payload),
  // Personal skills
  listSkills: (scene) => ipcRenderer.invoke("skills:list", scene),
  getSkill: (id) => ipcRenderer.invoke("skills:get", id),
  saveSkill: (skill) => ipcRenderer.invoke("skills:save", skill),
  deleteSkill: (id) => ipcRenderer.invoke("skills:delete", id),
  setActiveSkill: (payload) => ipcRenderer.invoke("skills:setActive", payload),
  getActiveSkill: (scene) => ipcRenderer.invoke("skills:getActive", scene),
  saveSkillFromContext: (payload) => ipcRenderer.invoke("skills:saveFromContext", payload),
  previewFeedback: (payload) => ipcRenderer.invoke("feedback:preview", payload),
  applyFeedback: (payload) => ipcRenderer.invoke("feedback:apply", payload),
  createDemoPackage: (opts) => ipcRenderer.invoke("packageStore:createDemo", opts),
  inspectPackageStore: (opts) => ipcRenderer.invoke("packageStore:inspect", opts),
  listPackageVersions: () => ipcRenderer.invoke("packageStore:listVersions"),
  getSubjectOverview: () => ipcRenderer.invoke("subject:getOverview"),
  rollbackPackageVersion: (payload) => ipcRenderer.invoke("packageStore:rollback", payload),
  recoverPackageStore: () => ipcRenderer.invoke("packageStore:recover"),
  planPpt: (payload) => ipcRenderer.invoke("output:planPpt", payload),
  savePpt: (plan) => ipcRenderer.invoke("output:savePpt", { plan }),
  // Capability extensions
  getExtensionsCatalog: () => ipcRenderer.invoke("extensions:getCatalog"),
  getExtensionsConfig: () => ipcRenderer.invoke("extensions:getConfig"),
  saveExtensionsConfig: (list) => ipcRenderer.invoke("extensions:saveConfig", list),
  enableExtension: (payload) => ipcRenderer.invoke("extensions:enable", payload),
  disableExtension: (id) => ipcRenderer.invoke("extensions:disable", id),
  pickExtensionDirectory: () => ipcRenderer.invoke("extensions:pickDirectory"),
  pickExtensionFile: () => ipcRenderer.invoke("extensions:pickFile"),
  getExtensionsStatus: () => ipcRenderer.invoke("extensions:getStatus"),
  connectExtension: (id) => ipcRenderer.invoke("extensions:connect", id),
  disconnectExtension: (id) => ipcRenderer.invoke("extensions:disconnect", id),
  listExtensionTools: (id) => ipcRenderer.invoke("extensions:listTools", id),
  callExtensionTool: (payload) => ipcRenderer.invoke("extensions:callTool", payload),
  openExternal: (url) => ipcRenderer.invoke("shell:openExternal", url),
  openPath: (target) => ipcRenderer.invoke("shell:openPath", target),
  l0AuditList: (opts) => ipcRenderer.invoke("l0:auditList", opts),
  decisionAuditList: (opts) => ipcRenderer.invoke("decisionAudit:list", opts),
  decisionAuditVerify: () => ipcRenderer.invoke("decisionAudit:verify"),
  decisionAuditRequestRotate: () => ipcRenderer.invoke("decisionAudit:requestRotate"),
  decisionAuditRotate: (payload) => ipcRenderer.invoke("decisionAudit:rotate", payload),
  l0ListAgents: () => ipcRenderer.invoke("l0:listAgents"),
  l0SetActiveAgent: (agentId) => ipcRenderer.invoke("l0:setActiveAgent", agentId),
  l0SaveCliAgent: (payload) => ipcRenderer.invoke("l0:saveCliAgent", payload),
  l0GetCliAgentConfig: () => ipcRenderer.invoke("l0:getCliAgentConfig"),
  l0BuildControlBrief: (payload) => ipcRenderer.invoke("l0:buildControlBrief", payload),
  l0RequestExternalAgent: (payload) => ipcRenderer.invoke("l0:requestExternalAgent", payload),
  l0CancelExternalAgentConfirmation: (payload) =>
    ipcRenderer.invoke("l0:cancelExternalAgentConfirmation", payload),
  l0RunExternalAgent: (payload) => ipcRenderer.invoke("l0:runExternalAgent", payload),
  l0StopExternalAgent: (payload) => ipcRenderer.invoke("l0:stopExternalAgent", payload),
  onExternalAgentStarted: (cb) => {
    const handler = (_e, data) => cb(data);
    ipcRenderer.on("l0:external-agent-started", handler);
    return () => ipcRenderer.removeListener("l0:external-agent-started", handler);
  },
  // Builder
  pickFile: () => ipcRenderer.invoke("builder:pickFile"),
  distill: (payload) => ipcRenderer.invoke("builder:distill", payload),
  cancelDistill: () => ipcRenderer.invoke("builder:cancel"),
  writeDistill: (payload) => ipcRenderer.invoke("builder:write", payload),
  getMaterialKinds: () => ipcRenderer.invoke("materials:kinds"),
  listCustody: () => ipcRenderer.invoke("materials:listCustody"),
  listInbox: () => ipcRenderer.invoke("inbox:list"),
  enqueueInbox: (files) => ipcRenderer.invoke("inbox:enqueue", files),
  removeInboxItem: (id) => ipcRenderer.invoke("inbox:remove", id),
  setInboxKind: (payload) => ipcRenderer.invoke("inbox:setKind", payload),
  organizeInbox: () => ipcRenderer.invoke("inbox:organize"),
  markInboxStatus: (payload) => ipcRenderer.invoke("inbox:markStatus", payload),
  onInboxProgress: (cb) => {
    const handler = (_e, data) => cb(data);
    ipcRenderer.on("inbox:progress", handler);
    return () => ipcRenderer.removeListener("inbox:progress", handler);
  },
  listAccessScopes: () => ipcRenderer.invoke("access:list"),
  addAccessScope: () => ipcRenderer.invoke("access:add"),
  removeAccessScope: (id) => ipcRenderer.invoke("access:remove"),
  scanAccessScopes: (scopeId) => ipcRenderer.invoke("access:scan", scopeId),
  getIntakeQuestions: () => ipcRenderer.invoke("intake:questions"),
  distillIntake: (payload) => ipcRenderer.invoke("intake:distill", payload),
  onBuilderProgress: (cb) => {
    const handler = (_e, data) => cb(data);
    ipcRenderer.on("builder:progress", handler);
    return () => ipcRenderer.removeListener("builder:progress", handler);
  },
});
